version: '3'
services:
  web:
    image: nicopaez/jobvacancy-ruby:1.3.0
    links:
      - db
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      RACK_ENV: "production"
      DATABASE_URL: "postgres://postgres@db:5432/postgres"
      DATABASE_PASSWORD_FILE: /run/secrets/postgres_password
    depends_on:
      - db
    secrets:
      - postgres_password
    command: ["/jobvacancy/start_app.sh"]
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
    restart: on-failure
    networks:
      - private
      - public

  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    networks:
      - private

secrets:
  postgres_password:
      file: ./postgres_password.txt

networks:
  private: {}
  public: {}
