apiVersion: v1
kind: Secret
metadata:
  name: jobvacancysecret
  labels:
    app: jobvacancy
data:
  DATABASE_URL: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOkZGX2N2Y1gzeEhXcXQ3azVCckBwb3N0Z3Jlczo1NDMyL3Bvc3RncmVz"
  POSTGRES_PASSWORD: "RkZfY3ZjWDN4SFdxdDdrNUJy"
