kind: Service
apiVersion: v1
metadata:
  name: jobvacancy
  labels:
    app: jobvacancy
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: jobvacancy
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
